### PR TITLE
Remove element from axis span calculations

### PR DESCRIPTION
**Pull request by ognjenst**

### CODE REVIEW

**Comment by mstijak** [comment]
After thorough consideration, I would recommend that we use the flag `affectsAxes` instead of `ignoreX(Y)`.
The problem is that the word affects doesn't have a nice antonym.
The property should not be bindable, and the default value `true` should be set on the prototype.


```jsx
<MarkerLine affectsAxes={false} />
```

**Comment by ognjenst** [comment]
It should be fine now.

**Comment by mstijak** [comment]
Looks good. There is just one more thing missing. Please add the flag to the documentation too. 

https://github.com/codaxy/cxjs/blob/master/docs/content/charts/configs/Marker.js

**Comment by ognjenst** [comment]
All done, both for Marker and MarkerLine.

**Pull request merged**
